kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: my-nodejs
          image: nodejs-image:latest
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: my-nodejs-svc
spec:
ports:
  - name: http-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
selector:
  app: nodejs-app
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: demo
  labels:
    app: app
    app.kubernetes.io/instance: nodejs
    app.kubernetes.io/managed-by: odo
    app.kubernetes.io/managed-by-version: v3.8.0
    app.kubernetes.io/part-of: app
    app.openshift.io/runtime: node.js
    component: nodejs
    odo.dev/mode: Dev
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: demo-odo-app.apps-crc.testing
  to:
    kind: Service
    name: my-nodejs-svc
    weight: 100
  port:
    targetPort: http-node
  wildcardPolicy: None
